import type { Metadata } from "next";
import { Arimo } from "next/font/google";
import "./globals.css";
import { twMerge } from "tailwind-merge";

const fonts = Arimo({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Clodron Parallel SaaS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={twMerge(fonts.className, "antialiased bg-[#EAEEFE]")}>
        {children}
      </body>
    </html>
  );
}
